/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AppUsageRouteImport } from './routes/app/usage'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppScannerRouteImport } from './routes/app/scanner'
import { Route as AppRssRouteImport } from './routes/app/rss'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppArticlesRouteImport } from './routes/app/articles'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppScannerRoute = AppScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRssRoute = AppRssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArticlesRoute = AppArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '/app/articles': typeof AppArticlesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/rss': typeof AppRssRoute
  '/app/scanner': typeof AppScannerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/usage': typeof AppUsageRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteRouteWithChildren
  '/app/articles': typeof AppArticlesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/rss': typeof AppRssRoute
  '/app/scanner': typeof AppScannerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/usage': typeof AppUsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteRouteWithChildren
  '/app/articles': typeof AppArticlesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/rss': typeof AppRssRoute
  '/app/scanner': typeof AppScannerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/usage': typeof AppUsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/app/articles'
    | '/app/dashboard'
    | '/app/rss'
    | '/app/scanner'
    | '/app/settings'
    | '/app/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/app/articles'
    | '/app/dashboard'
    | '/app/rss'
    | '/app/scanner'
    | '/app/settings'
    | '/app/usage'
  id:
    | '__root__'
    | '/app'
    | '/app/articles'
    | '/app/dashboard'
    | '/app/rss'
    | '/app/scanner'
    | '/app/settings'
    | '/app/usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/usage': {
      id: '/app/usage'
      path: '/usage'
      fullPath: '/app/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/scanner': {
      id: '/app/scanner'
      path: '/scanner'
      fullPath: '/app/scanner'
      preLoaderRoute: typeof AppScannerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/rss': {
      id: '/app/rss'
      path: '/rss'
      fullPath: '/app/rss'
      preLoaderRoute: typeof AppRssRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/articles': {
      id: '/app/articles'
      path: '/articles'
      fullPath: '/app/articles'
      preLoaderRoute: typeof AppArticlesRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppArticlesRoute: typeof AppArticlesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppRssRoute: typeof AppRssRoute
  AppScannerRoute: typeof AppScannerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsageRoute: typeof AppUsageRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppArticlesRoute: AppArticlesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppRssRoute: AppRssRoute,
  AppScannerRoute: AppScannerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsageRoute: AppUsageRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
