/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AppScannerRouteImport } from './routes/app/scanner'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppArticlesRouteImport } from './routes/app/articles'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScannerRoute = AppScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArticlesRoute = AppArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '/app/articles': typeof AppArticlesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/scanner': typeof AppScannerRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteRouteWithChildren
  '/app/articles': typeof AppArticlesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/scanner': typeof AppScannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteRouteWithChildren
  '/app/articles': typeof AppArticlesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/scanner': typeof AppScannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/app' | '/app/articles' | '/app/dashboard' | '/app/scanner'
  fileRoutesByTo: FileRoutesByTo
  to: '/app' | '/app/articles' | '/app/dashboard' | '/app/scanner'
  id: '__root__' | '/app' | '/app/articles' | '/app/dashboard' | '/app/scanner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/scanner': {
      id: '/app/scanner'
      path: '/scanner'
      fullPath: '/app/scanner'
      preLoaderRoute: typeof AppScannerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/articles': {
      id: '/app/articles'
      path: '/articles'
      fullPath: '/app/articles'
      preLoaderRoute: typeof AppArticlesRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppArticlesRoute: typeof AppArticlesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppScannerRoute: typeof AppScannerRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppArticlesRoute: AppArticlesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppScannerRoute: AppScannerRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
